baseURL = "https://xss3cut10n3r.me/"
theme = "loficode"
title = "XSS3cut10n3r"

[params]
  description = "Your site description"
  tagline = "Don’t tell people your plans.  \nShow them your results."
  headerText = "XSS3cut10n3r"

[params.author]
  name = "XSS3cut10n3r"
  image = "/images/profile.png"

[params.social]
  email = "contact@xss3cut10n3r.me"
  github = "https://github.com/xss3cut10n3r"

[[menu.main]]
  name = "Tags"
  url = '/tags/'
  weight = 2

[[menu.main]]
  name = "HTB"
  url = "https://app.hackthebox.com/profile/2280564"
  weight = 3
  [menu.main.params]
    target = "_blank"
    rel = "noopener noreferrer"

[markup.goldmark.renderer]
  unsafe = true
